
version: '3.8'
services:

  app:
    build: .
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgres/data

  redis:
    image: redis:7-alpine
    environment:
      - REDIS_PASSWORD=secret
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
